name: Generate Calendar
on:
  workflow_dispatch: # allows requesting workflow manually from the website
jobs:
  generate-calendar:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/lowlighter/metrics/tree/master/source/plugins/calendar
      - name: 'metrics: calendar (current)'
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.calendar.current.svg
          base: ''
          plugin_calendar: yes

      # https://github.com/lowlighter/metrics/tree/master/source/plugins/calendar
      - name: 'metrics: calendar (full)'
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.calendar.full.svg
          base: ''
          plugin_calendar: yes
          plugin_calendar_limit: 0
