name: Generate Steam
on:
  workflow_dispatch: # allows requesting workflow manually from the website
jobs:
  generate-steam:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/lowlighter/metrics/tree/master/source/plugins/steam
      - name: 'metrics: steam (recently played games)'
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.steam.recent.svg
          token: NOT_NEEDED
          base: ''
          plugin_steam: yes
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam_user: 76561198053036362
          plugin_steam_sections: recently-played
          plugin_steam_achievements_limit: 0

      # https://github.com/lowlighter/metrics/tree/master/source/plugins/steam
      - name: 'metrics: steam (profile and detailed game history)'
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.steam.full.svg
          token: NOT_NEEDED
          base: ''
          plugin_steam: yes
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam_user: 76561198053036362
          plugin_steam_sections: player, most-played, recently-played
