name: Generate All Metrics
on:
  schedule: # [{ cron: '0 0 * * 1' }] # Schedule daily updates
    - cron: '0 0 * * 1' # Every Monday at 00:00 AM UTC
    - cron: '0 15 * * 3' # Every Wednesday at 03:00 PM UTC
    - cron: '0 6 * * 5' # Every Friday at 06:00 AM UTC
  workflow_dispatch: # allows requesting workflow manually from the website
  # push: { branches: ['main'] } # Run workflow when pushing on master/main
  push:
    paths:
      - '.github/workflows/metrics.yml' # run workflow if metrics.yml changes
jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    if: "github.repository == 'elfensky/elfensky'" #this isn't really neccesary, but needs testing.
    steps:
      # https://github.com/lowlighter/metrics/blob/master/source/plugins/base/README.md
      - name: 'metrics: base'
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.base.svg
          config_timezone: Europe/Brussels
          base: header, activity, community, repositories, metadata
          base_indepth: yes

      # https://github.com/lowlighter/metrics/tree/master/source/plugins/languages
      - name: 'metrics: languages'
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.languages.svg
          config_timezone: Europe/Brussels
          base: ''
          plugin_languages: yes
          plugin_languages_indepth: yes

      # https://github.com/lowlighter/metrics/tree/master/source/plugins/habits
      - name: 'metrics: habits (facts)'
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.habits.facts.svg
          config_timezone: Europe/Brussels
          base: ''
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          plugin_habits_from: 512
          plugin_habits_charts_type: classic
          # plugin_habits_trim: no

      # https://github.com/lowlighter/metrics/tree/master/source/plugins/habits
      - name: 'metrics: habits (charts)'
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.habits.charts.svg
          config_timezone: Europe/Brussels
          base: ''
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugin_habits_from: 512
          plugin_habits_charts_type: classic
          # plugin_habits_trim: no

      # https://github.com/lowlighter/metrics/tree/master/source/plugins/pagespeed
      # - name: 'metrics: pagespeed'
      #   if: ${{ success() || failure() }}
      #   uses: lowlighter/metrics@latest
      #   with:
      #     token: NOT_NEEDED
      #     filename: metrics.plugin.pagespeed.svg
      #     base: ''
      #     base_skip: yes
      #     plugin_pagespeed: yes
      #     plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
      #     plugin_pagespeed_detailed: yes
      #     plugin_pagespeed_screenshot: no
      #     plugin_pagespeed_pwa: no
      #     plugin_pagespeed_url: https://lavrenov.io

      # https://github.com/lowlighter/metrics/tree/master/source/plugins/achievements
      - name: 'metrics: achievements (compact)'
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.achievements.compact.svg
          base: ''
          plugin_achievements: yes
          plugin_achievements_display: compact #detailed is default

      # https://github.com/lowlighter/metrics/tree/master/source/plugins/achievements
      - name: 'metrics: achievements (full)'
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.achievements.full.svg
          base: ''
          plugin_achievements: yes

      # https://github.com/lowlighter/metrics/tree/master/source/plugins/calendar
      - name: 'metrics: calendar (current)'
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.calendar.current.svg
          base: ''
          plugin_calendar: yes

      # https://github.com/lowlighter/metrics/tree/master/source/plugins/calendar
      # - name: "metrics: calendar (full)"
      #   if: ${{ success() || failure() }}
      #   uses: lowlighter/metrics@latest
      #   with:
      #     token: ${{ secrets.METRICS_TOKEN }}
      #     filename: metrics.plugin.calendar.full.svg
      #     base: ""
      #     plugin_calendar: yes
      #     plugin_calendar_limit: 0

      # https://github.com/lowlighter/metrics/tree/master/source/plugins/wakatime
      - name: 'metrics: wakapi'
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.wakapi.svg
          token: NOT_NEEDED
          base: ''
          base_skip: yes
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKAPI_TOKEN }}
          plugin_wakatime_url: https://wakapi.lavrenov.io
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_days: 365

      # https://github.com/lowlighter/metrics/tree/master/source/plugins/steam
      # - name: "metrics: steam"
      #   if: ${{ success() || failure() }}
      #   uses: elfensky/metrics@latest
      #   with:
      #     token: NOT_NEEDED
      #     filename: metrics.plugin.steam.svg
      #     base: ""
      #     plugin_steam: yes
      #     plugin_steam_sections: player, most-played. recently-played
      #     plugin_steam_user: 76561198053036362
