name: Generate All Metrics
on:
  schedule: # [{ cron: '0 0 * * 1' }] # Schedule daily updates
    - cron: '0 0 * * 1' # Every Monday at 00:00 AM UTC
    - cron: '0 15 * * 3' # Every Wednesday at 03:00 PM UTC
    - cron: '0 6 * * 5' # Every Friday at 06:00 AM UTC
  workflow_dispatch: # allows requesting workflow manually from the website
  # push: { branches: ['main'] } # Run workflow when pushing on master/main
  push:
    paths:
      - '.github/workflows/metrics.yml' # run workflow if metrics.yml changes
jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/lowlighter/metrics/blob/master/source/plugins/base/README.md
      - name: 'metrics: base'
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.base.svg
          config_timezone: Europe/Brussels
          base: header, activity, community, repositories, metadata
          base_indepth: yes

      # https://github.com/lowlighter/metrics/tree/master/source/plugins/languages
      - name: 'metrics: languages'
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.languages.svg
          config_timezone: Europe/Brussels
          base: ''
          plugin_languages: yes
          plugin_languages_indepth: yes

      # https://github.com/lowlighter/metrics/tree/master/source/plugins/habits
      - name: 'metrics: habits (facts)'
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.habits.svg
          config_timezone: Europe/Brussels
          base: ''
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_from: 512
          plugin_habits_charts_type: classic
          plugin_habits_trim: no

      # https://github.com/lowlighter/metrics/tree/master/source/plugins/achievements
      - name: 'metrics: achievements'
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.achievements.svg
          base: ''
          plugin_achievements: yes

      # https://github.com/lowlighter/metrics/tree/master/source/plugins/calendar
      - name: 'metrics: calendar'
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.calendar.svg
          base: ''
          plugin_calendar: yes

      # https://github.com/lowlighter/metrics/tree/master/source/plugins/wakatime
      - name: 'metrics: wakapi'
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.wakapi.svg
          token: NOT_NEEDED
          base: ''
          base_skip: yes
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKAPI_TOKEN }}
          plugin_wakatime_url: https://wakapi.lavrenov.io
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_days: 365
